name: CI for C server

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  server-ci:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check formatting
      uses: jidicula/clang-format-action@v4.11.0
      with:
        clang-format-version: '16'
        check-path: 'server/src'
    - name: Check linting
      uses: HorstBaerbel/action-clang-tidy@1.2
      with:
        scandir: 'server'
